# ==== pytest ====
[tool.pytest.ini_options]
minversion = "6.0"
python_files = [
    "tests.py",
    "test_*.py",
]

# ==== black ====
[tool.black]
line-length = 119
target-version = ['py311']

# ==== isort ====
[tool.isort]
profile = "black"
line_length = 119
known_first_party = [
    "creation",
    "structural",
    "behavior"
]
skip = [".venv/"]
